---@param p TokenPalette
---@return table<string, vim.api.keyset.highlight>
local function blink(p)
  return {
    BlinkCmpMenu = { fg = p.fg0, bg = p.bg1 },
    BlinkCmpMenuBorder = { fg = p.fg3, bg = p.bg1 },
    BlinkCmpMenuSelection = { bg = p.sel, bold = true },
    BlinkCmpScrollBarThumb = { bg = p.fg3 },
    BlinkCmpScrollBarGutter = { bg = p.bg2 },
    BlinkCmpLabel = { fg = p.fg0 },
    BlinkCmpLabelDeprecated = { fg = p.fg3, strikethrough = true },
    BlinkCmpLabelMatch = { fg = p.accent, bold = true },
    BlinkCmpLabelDetail = { fg = p.fg2 },
    BlinkCmpLabelDescription = { fg = p.fg2 },
    BlinkCmpKind = { fg = p.fg2 },
    BlinkCmpKindText = { fg = p.fg1 },
    BlinkCmpKindMethod = { fg = p.accent },
    BlinkCmpKindFunction = { fg = p.accent },
    BlinkCmpKindConstructor = { fg = p.blue },
    BlinkCmpKindField = { fg = p.fg0 },
    BlinkCmpKindVariable = { fg = p.fg0 },
    BlinkCmpKindClass = { fg = p.blue },
    BlinkCmpKindInterface = { fg = p.blue },
    BlinkCmpKindModule = { fg = p.blue },
    BlinkCmpKindProperty = { fg = p.fg0 },
    BlinkCmpKindUnit = { fg = p.purple },
    BlinkCmpKindValue = { fg = p.purple },
    BlinkCmpKindEnum = { fg = p.blue },
    BlinkCmpKindKeyword = { fg = p.accent2 },
    BlinkCmpKindSnippet = { fg = p.green },
    BlinkCmpKindColor = { fg = p.purple },
    BlinkCmpKindFile = { fg = p.blue },
    BlinkCmpKindReference = { fg = p.blue },
    BlinkCmpKindFolder = { fg = p.blue },
    BlinkCmpKindEnumMember = { fg = p.purple },
    BlinkCmpKindConstant = { fg = p.purple },
    BlinkCmpKindStruct = { fg = p.blue },
    BlinkCmpKindEvent = { fg = p.accent2 },
    BlinkCmpKindOperator = { fg = p.fg1 },
    BlinkCmpKindTypeParameter = { fg = p.blue },
    BlinkCmpDoc = { fg = p.fg0, bg = p.bg0 },
    BlinkCmpDocBorder = { fg = p.fg3, bg = p.bg0 },
    BlinkCmpDocSeparator = { fg = p.fg3, bg = p.bg0 },
    BlinkCmpDocCursorLine = { bg = p.bg5 },
    BlinkCmpSignatureHelp = { fg = p.fg0, bg = p.bg0 },
    BlinkCmpSignatureHelpBorder = { fg = p.fg3, bg = p.bg0 },
    BlinkCmpSignatureHelpActiveParameter = { fg = p.accent, bold = true },
    BlinkCmpGhostText = { fg = p.fg3, italic = true },
    BlinkCmpSource = { fg = p.fg2 },
  }
end

return blink
