---@param p TokenPalette
---@return table<string, vim.api.keyset.highlight>
local function neogit(p)
  return {
    NeogitBranch = { fg = p.accent },
    NeogitRemote = { fg = p.blue },
    NeogitHunkHeader = { fg = p.fg0, bg = p.bg4, bold = true },
    NeogitHunkHeaderHighlight = { fg = p.accent, bg = p.bg5, bold = true },
    NeogitDiffAdd = { fg = p.green, bg = p.diff_add },
    NeogitDiffDelete = { fg = p.red, bg = p.diff_del },
    NeogitDiffContext = { fg = p.fg1, bg = p.bg3 },
    NeogitDiffContextHighlight = { fg = p.fg0, bg = p.bg4 },
    NeogitDiffAddHighlight = { fg = p.green, bg = p.diff_add, bold = true },
    NeogitDiffDeleteHighlight = { fg = p.red, bg = p.diff_del, bold = true },
    NeogitDiffAddInline = { bg = p.diff_add_inline },
    NeogitDiffDeleteInline = { bg = p.diff_del_inline },
    NeogitChangeModified = { fg = p.yellow },
    NeogitChangeAdded = { fg = p.green },
    NeogitChangeDeleted = { fg = p.red },
    NeogitChangeRenamed = { fg = p.purple },
    NeogitChangeNewFile = { fg = p.green },
    NeogitChangeUpdated = { fg = p.blue },
    NeogitChangeCopied = { fg = p.accent2 },
    NeogitChangeUnmerged = { fg = p.accent },
    NeogitUnpushedTo = { fg = p.accent },
    NeogitUnpulledFrom = { fg = p.blue },
    NeogitSectionHeader = { fg = p.accent, bold = true },
    NeogitStash = { fg = p.fg1 },
    NeogitStashEntry = { fg = p.fg0 },
    NeogitObjectId = { fg = p.fg3 },
    NeogitGraphBlue = { fg = p.blue },
    NeogitGraphRed = { fg = p.red },
    NeogitGraphWhite = { fg = p.fg0 },
    NeogitGraphGray = { fg = p.fg3 },
    NeogitGraphGreen = { fg = p.green },
    NeogitGraphYellow = { fg = p.yellow },
    NeogitGraphOrange = { fg = p.accent },
    NeogitGraphPurple = { fg = p.purple },
    NeogitGraphBoldBlue = { fg = p.blue, bold = true },
    NeogitGraphBoldRed = { fg = p.red, bold = true },
    NeogitGraphBoldWhite = { fg = p.fg0, bold = true },
    NeogitGraphBoldGray = { fg = p.fg3, bold = true },
    NeogitGraphBoldGreen = { fg = p.green, bold = true },
    NeogitGraphBoldYellow = { fg = p.yellow, bold = true },
    NeogitGraphBoldOrange = { fg = p.accent, bold = true },
    NeogitGraphBoldPurple = { fg = p.purple, bold = true },
  }
end

return neogit
