---@param p TokenPalette
---@return table<string, vim.api.keyset.highlight>
local function trouble(p)
  return {
    TroubleNormal = { fg = p.fg0, bg = p.bg1 },
    TroubleNormalNC = { fg = p.fg0, bg = p.bg1 },
    TroubleCount = { fg = p.accent, bold = true },
    TroubleText = { fg = p.fg0 },
    TroubleCode = { fg = p.fg2 },
    TroubleSource = { fg = p.fg2 },
    TroublePos = { fg = p.fg3 },
    TroubleBasename = { fg = p.fg0, bold = true },
    TroubleDirectory = { fg = p.blue },
    TroubleFilename = { fg = p.fg0 },
    TroublePreview = { bg = p.bg4 },
    TroubleIndent = { fg = p.fg3 },
    TroubleIndentFoldOpen = { fg = p.accent },
    TroubleIndentFoldClosed = { fg = p.fg3 },
    TroubleIndentWs = { fg = p.fg3 },
    TroubleIndentTop = { fg = p.fg3 },
    TroubleIndentMiddle = { fg = p.fg3 },
    TroubleIndentLast = { fg = p.fg3 },
    TroubleIconArray = { fg = p.blue },
    TroubleIconBoolean = { fg = p.purple },
    TroubleIconClass = { fg = p.blue },
    TroubleIconConstant = { fg = p.purple },
    TroubleIconConstructor = { fg = p.blue },
    TroubleIconDirectory = { fg = p.blue },
    TroubleIconEnum = { fg = p.blue },
    TroubleIconEnumMember = { fg = p.purple },
    TroubleIconEvent = { fg = p.accent2 },
    TroubleIconField = { fg = p.fg0 },
    TroubleIconFile = { fg = p.fg0 },
    TroubleIconFunction = { fg = p.accent },
    TroubleIconInterface = { fg = p.blue },
    TroubleIconKey = { fg = p.fg0 },
    TroubleIconMethod = { fg = p.accent },
    TroubleIconModule = { fg = p.blue },
    TroubleIconNamespace = { fg = p.blue },
    TroubleIconNull = { fg = p.purple },
    TroubleIconNumber = { fg = p.purple },
    TroubleIconObject = { fg = p.blue },
    TroubleIconOperator = { fg = p.fg1 },
    TroubleIconPackage = { fg = p.blue },
    TroubleIconProperty = { fg = p.fg0 },
    TroubleIconString = { fg = p.green },
    TroubleIconStruct = { fg = p.blue },
    TroubleIconTypeParameter = { fg = p.blue },
    TroubleIconVariable = { fg = p.fg0 },
  }
end

return trouble
