# Generated by token colorscheme. Do not edit manually.
# Source this file from config.fish to append token colors to FZF_DEFAULT_OPTS.

set -gx FZF_DEFAULT_OPTS (string join " " -- \
  $FZF_DEFAULT_OPTS \
  --border \
  '--color=fg:#2a2920,bg:#faf9f5,hl:#9a4929' \
  '--color=fg+:#2a2920,bg+:#dddcd6,hl+:#9a4929' \
  '--color=border:#858179,header:#527594,gutter:#faf9f5' \
  '--color=spinner:#876032,info:#6c675f' \
  '--color=pointer:#9a4929,marker:#3f643c,prompt:#9a4929')
