---@param p table palette
---@return table
local function plugins(p)
  return {
    -- blink.cmp
    BlinkCmpMenu = { fg = p.fg0, bg = p.bg1 },
    BlinkCmpMenuBorder = { fg = p.fg3, bg = p.bg1 },
    BlinkCmpMenuSelection = { bg = p.sel, bold = true },
    BlinkCmpScrollBarThumb = { bg = p.fg3 },
    BlinkCmpScrollBarGutter = { bg = p.bg2 },
    BlinkCmpLabel = { fg = p.fg0 },
    BlinkCmpLabelDeprecated = { fg = p.fg3, strikethrough = true },
    BlinkCmpLabelMatch = { fg = p.accent, bold = true },
    BlinkCmpLabelDetail = { fg = p.fg2 },
    BlinkCmpLabelDescription = { fg = p.fg2 },
    BlinkCmpKind = { fg = p.fg2 },
    BlinkCmpKindText = { fg = p.fg1 },
    BlinkCmpKindMethod = { fg = p.accent },
    BlinkCmpKindFunction = { fg = p.accent },
    BlinkCmpKindConstructor = { fg = p.blue },
    BlinkCmpKindField = { fg = p.fg0 },
    BlinkCmpKindVariable = { fg = p.fg0 },
    BlinkCmpKindClass = { fg = p.blue },
    BlinkCmpKindInterface = { fg = p.blue },
    BlinkCmpKindModule = { fg = p.blue },
    BlinkCmpKindProperty = { fg = p.fg0 },
    BlinkCmpKindUnit = { fg = p.purple },
    BlinkCmpKindValue = { fg = p.purple },
    BlinkCmpKindEnum = { fg = p.blue },
    BlinkCmpKindKeyword = { fg = p.accent2 },
    BlinkCmpKindSnippet = { fg = p.green },
    BlinkCmpKindColor = { fg = p.purple },
    BlinkCmpKindFile = { fg = p.blue },
    BlinkCmpKindReference = { fg = p.blue },
    BlinkCmpKindFolder = { fg = p.blue },
    BlinkCmpKindEnumMember = { fg = p.purple },
    BlinkCmpKindConstant = { fg = p.purple },
    BlinkCmpKindStruct = { fg = p.blue },
    BlinkCmpKindEvent = { fg = p.accent2 },
    BlinkCmpKindOperator = { fg = p.fg1 },
    BlinkCmpKindTypeParameter = { fg = p.blue },
    BlinkCmpDoc = { fg = p.fg0, bg = p.bg0 },
    BlinkCmpDocBorder = { fg = p.fg3, bg = p.bg0 },
    BlinkCmpDocSeparator = { fg = p.fg3, bg = p.bg0 },
    BlinkCmpDocCursorLine = { bg = p.bg5 },
    BlinkCmpSignatureHelp = { fg = p.fg0, bg = p.bg0 },
    BlinkCmpSignatureHelpBorder = { fg = p.fg3, bg = p.bg0 },
    BlinkCmpSignatureHelpActiveParameter = { fg = p.accent, bold = true },
    BlinkCmpGhostText = { fg = p.fg3, italic = true },
    BlinkCmpSource = { fg = p.fg2 },

    -- vim-matchup
    MatchWord = { bg = p.bg5 },
    MatchWordCur = { bg = p.bg5 },
    MatchParenCur = { fg = p.accent, bold = true, underline = true },

    -- indent-blankline
    IblIndent = { fg = p.indent },
    IblScope = { fg = p.indent_active },
    IblWhitespace = { fg = p.indent },

    -- hlchunk.nvim
    HLChunk1 = { fg = p.indent_active },
    HLChunk2 = { fg = p.red },
    HLIndent1 = { fg = p.indent },
    HLLineNum1 = { fg = p.indent_active },
    HLBlank1 = { fg = p.indent },

    -- markview.nvim palette (foundation, headings/callouts/checkboxes link here)
    MarkviewPalette0 = { fg = p.fg2, bg = p.bg4 },
    MarkviewPalette0Sign = { fg = p.fg2 },
    MarkviewPalette0Fg = { fg = p.fg2 },
    MarkviewPalette0Bg = { bg = p.bg4 },

    MarkviewPalette1 = { fg = p.accent, bg = p.bg4 },
    MarkviewPalette1Sign = { fg = p.accent },
    MarkviewPalette1Fg = { fg = p.accent },
    MarkviewPalette1Bg = { bg = p.bg4 },

    MarkviewPalette2 = { fg = p.accent2, bg = p.bg4 },
    MarkviewPalette2Sign = { fg = p.accent2 },
    MarkviewPalette2Fg = { fg = p.accent2 },
    MarkviewPalette2Bg = { bg = p.bg4 },

    MarkviewPalette3 = { fg = p.yellow, bg = p.bg4 },
    MarkviewPalette3Sign = { fg = p.yellow },
    MarkviewPalette3Fg = { fg = p.yellow },
    MarkviewPalette3Bg = { bg = p.bg4 },

    MarkviewPalette4 = { fg = p.blue, bg = p.bg4 },
    MarkviewPalette4Sign = { fg = p.blue },
    MarkviewPalette4Fg = { fg = p.blue },
    MarkviewPalette4Bg = { bg = p.bg4 },

    MarkviewPalette5 = { fg = p.green, bg = p.bg4 },
    MarkviewPalette5Sign = { fg = p.green },
    MarkviewPalette5Fg = { fg = p.green },
    MarkviewPalette5Bg = { bg = p.bg4 },

    MarkviewPalette6 = { fg = p.purple, bg = p.bg4 },
    MarkviewPalette6Sign = { fg = p.purple },
    MarkviewPalette6Fg = { fg = p.purple },
    MarkviewPalette6Bg = { bg = p.bg4 },

    MarkviewPalette7 = { fg = p.cyan, bg = p.bg4 },
    MarkviewPalette7Sign = { fg = p.cyan },
    MarkviewPalette7Fg = { fg = p.cyan },
    MarkviewPalette7Bg = { bg = p.bg4 },

    -- markview.nvim code blocks
    MarkviewCode = { bg = p.bg2 },
    MarkviewCodeInfo = { fg = p.fg2, bg = p.bg2 },
    MarkviewCodeFg = { fg = p.fg3 },
    MarkviewInlineCode = { fg = p.green, bg = p.bg2 },

    -- markview.nvim block quotes (override palette links for semantic colors)
    MarkviewBlockQuoteDefault = { fg = p.fg2 },
    MarkviewBlockQuoteError = { fg = p.red },
    MarkviewBlockQuoteWarn = { fg = p.yellow },
    MarkviewBlockQuoteSpecial = { fg = p.accent2 },
    MarkviewBlockQuoteOk = { fg = p.green },
    MarkviewBlockQuoteNote = { fg = p.blue },

    -- markview.nvim checkboxes (override palette links for semantic colors)
    MarkviewCheckboxChecked = { fg = p.green },
    MarkviewCheckboxUnchecked = { fg = p.fg3 },
    MarkviewCheckboxPending = { fg = p.accent2 },
    MarkviewCheckboxProgress = { fg = p.blue },
    MarkviewCheckboxCancelled = { fg = p.fg2 },
    MarkviewCheckboxStriked = { fg = p.fg2, strikethrough = true },

    -- markview.nvim horizontal rule gradient (bg3 → accent)
    MarkviewGradient0 = { fg = p.bg5 },
    MarkviewGradient1 = { fg = p.fg3 },
    MarkviewGradient2 = { fg = p.fg3 },
    MarkviewGradient3 = { fg = p.fg2 },
    MarkviewGradient4 = { fg = p.fg2 },
    MarkviewGradient5 = { fg = p.fg2 },
    MarkviewGradient6 = { fg = p.fg1 },
    MarkviewGradient7 = { fg = p.fg1 },
    MarkviewGradient8 = { fg = p.accent2 },
    MarkviewGradient9 = { fg = p.accent },

    -- oil.nvim
    OilDir = { fg = p.blue },
    OilFile = { fg = p.fg0 },
    OilLink = { fg = p.purple },
    OilLinkTarget = { fg = p.purple, italic = true },
    OilSocket = { fg = p.accent2 },
    OilOrphanLink = { fg = p.red },
    OilOrphanLinkTarget = { fg = p.red, italic = true },
    OilCreate = { fg = p.green },
    OilDelete = { fg = p.red },
    OilMove = { fg = p.accent2 },
    OilCopy = { fg = p.yellow },
    OilChange = { fg = p.blue },
    OilPermissionNone = { fg = p.fg3 },
    OilPermissionRead = { fg = p.yellow },
    OilPermissionWrite = { fg = p.red },
    OilPermissionExecute = { fg = p.green },
    OilTypeDir = { fg = p.blue },
    OilTypeFile = { fg = p.fg2 },
    OilTypeLink = { fg = p.purple },
    OilTypeSocket = { fg = p.accent2 },

    -- gitsigns
    GitSignsAdd = { fg = p.gsign_add },
    GitSignsChange = { fg = p.gsign_change },
    GitSignsDelete = { fg = p.gsign_del },
    GitSignsTopDelete = { fg = p.gsign_del },
    GitSignsChangeDelete = { fg = p.accent },
    GitSignsUntracked = { fg = p.gsign_untracked },
    GitSignsAddNr = { link = 'GitSignsAdd' },
    GitSignsChangeNr = { link = 'GitSignsChange' },
    GitSignsDeleteNr = { link = 'GitSignsDelete' },
    GitSignsAddLn = { bg = p.diff_add },
    GitSignsChangeLn = { bg = p.diff_change },
    GitSignsDeleteLn = { bg = p.diff_del },
    GitSignsAddPreview = { bg = p.diff_add },
    GitSignsDeletePreview = { bg = p.diff_del },
    GitSignsCurrentLineBlame = { fg = p.fg3, italic = true },

    -- neogit
    NeogitBranch = { fg = p.accent },
    NeogitRemote = { fg = p.blue },
    NeogitHunkHeader = { fg = p.fg0, bg = p.bg4, bold = true },
    NeogitHunkHeaderHighlight = { fg = p.accent, bg = p.bg5, bold = true },
    NeogitDiffAdd = { fg = p.green, bg = p.diff_add },
    NeogitDiffDelete = { fg = p.red, bg = p.diff_del },
    NeogitDiffContext = { fg = p.fg1, bg = p.bg3 },
    NeogitDiffContextHighlight = { fg = p.fg0, bg = p.bg4 },
    NeogitDiffAddHighlight = { fg = p.green, bg = p.diff_add, bold = true },
    NeogitDiffDeleteHighlight = { fg = p.red, bg = p.diff_del, bold = true },
    NeogitDiffAddInline = { bg = p.diff_add_inline },
    NeogitDiffDeleteInline = { bg = p.diff_del_inline },
    NeogitChangeModified = { fg = p.yellow },
    NeogitChangeAdded = { fg = p.green },
    NeogitChangeDeleted = { fg = p.red },
    NeogitChangeRenamed = { fg = p.purple },
    NeogitChangeNewFile = { fg = p.green },
    NeogitChangeUpdated = { fg = p.blue },
    NeogitChangeCopied = { fg = p.accent2 },
    NeogitChangeUnmerged = { fg = p.accent },
    NeogitUnpushedTo = { fg = p.accent },
    NeogitUnpulledFrom = { fg = p.blue },
    NeogitSectionHeader = { fg = p.accent, bold = true },
    NeogitStash = { fg = p.fg1 },
    NeogitStashEntry = { fg = p.fg0 },
    NeogitObjectId = { fg = p.fg3 },
    NeogitGraphBlue = { fg = p.blue },
    NeogitGraphRed = { fg = p.red },
    NeogitGraphWhite = { fg = p.fg0 },
    NeogitGraphGray = { fg = p.fg3 },
    NeogitGraphGreen = { fg = p.green },
    NeogitGraphYellow = { fg = p.yellow },
    NeogitGraphOrange = { fg = p.accent },
    NeogitGraphPurple = { fg = p.purple },
    NeogitGraphBoldBlue = { fg = p.blue, bold = true },
    NeogitGraphBoldRed = { fg = p.red, bold = true },
    NeogitGraphBoldWhite = { fg = p.fg0, bold = true },
    NeogitGraphBoldGray = { fg = p.fg3, bold = true },
    NeogitGraphBoldGreen = { fg = p.green, bold = true },
    NeogitGraphBoldYellow = { fg = p.yellow, bold = true },
    NeogitGraphBoldOrange = { fg = p.accent, bold = true },
    NeogitGraphBoldPurple = { fg = p.purple, bold = true },

    -- diffview
    DiffviewFilePanelRootPath = { fg = p.fg3 },
    DiffviewFilePanelTitle = { fg = p.accent, bold = true },
    DiffviewFilePanelCounter = { fg = p.fg2 },
    DiffviewFilePanelFileName = { fg = p.fg0 },
    DiffviewFilePanelInsertions = { fg = p.green },
    DiffviewFilePanelDeletions = { fg = p.red },
    DiffviewFilePanelConflicts = { fg = p.yellow },
    DiffviewFolderName = { fg = p.blue },
    DiffviewFolderSign = { fg = p.fg3 },
    DiffviewStatusAdded = { fg = p.green },
    DiffviewStatusUntracked = { fg = p.fg3 },
    DiffviewStatusModified = { fg = p.yellow },
    DiffviewStatusRenamed = { fg = p.purple },
    DiffviewStatusCopied = { fg = p.accent2 },
    DiffviewStatusTypeChange = { fg = p.blue },
    DiffviewStatusUnmerged = { fg = p.accent },
    DiffviewStatusUnknown = { fg = p.red },
    DiffviewStatusDeleted = { fg = p.red },
    DiffviewStatusBroken = { fg = p.red, bold = true },
    DiffviewStatusIgnored = { fg = p.fg3 },

    -- vim-fugitive (status buffer)
    fugitiveHeader = { fg = p.accent2, bold = true },
    fugitiveHelpHeader = { link = 'fugitiveHeader' },
    fugitiveHelpTag = { fg = p.fg2 },
    fugitiveHeading = { fg = p.accent, bold = true },
    fugitiveUntrackedHeading = { fg = p.fg2, bold = true },
    fugitiveUnstagedHeading = { fg = p.yellow, bold = true },
    fugitiveStagedHeading = { fg = p.green, bold = true },
    fugitiveCount = { fg = p.fg2 },
    fugitiveModifier = { fg = p.blue },
    fugitiveUntrackedModifier = { fg = p.fg3 },
    fugitiveUnstagedModifier = { fg = p.yellow },
    fugitiveStagedModifier = { fg = p.green },
    fugitiveInstruction = { fg = p.accent2 },
    fugitiveStop = { fg = p.red, bold = true },
    fugitiveHash = { fg = p.fg3 },
    fugitiveSymbolicRef = { fg = p.accent },

    -- vim-fugitive (blame buffer)
    FugitiveblameBoundary = { fg = p.accent2 },
    FugitiveblameHash = { fg = p.fg3 },
    FugitiveblameBoundaryIgnore = { link = 'Ignore' },
    FugitiveblameUncommitted = { link = 'Ignore' },
    FugitiveblameScoreDebug = { link = 'Debug' },
    FugitiveblameTime = { fg = p.fg2 },
    FugitiveblameLineNumber = { fg = p.fg3 },
    FugitiveblameOriginalFile = { fg = p.fg2 },
    FugitiveblameOriginalLineNumber = { fg = p.fg3 },
    FugitiveblameShort = { link = 'FugitiveblameDelimiter' },
    FugitiveblameDelimiter = { fg = p.fg3 },
    FugitiveblameNotCommittedYet = { link = 'Comment' },

    -- mason
    MasonHeader = { fg = p.bg3, bg = p.accent, bold = true },
    MasonHeaderSecondary = { fg = p.bg3, bg = p.accent2, bold = true },
    MasonHighlight = { fg = p.accent },
    MasonHighlightBlock = { fg = p.bg3, bg = p.accent },
    MasonHighlightBlockBold = { fg = p.bg3, bg = p.accent, bold = true },
    MasonHighlightSecondary = { fg = p.accent2 },
    MasonHighlightBlockSecondary = { fg = p.bg3, bg = p.accent2 },
    MasonHighlightBlockBoldSecondary = { fg = p.bg3, bg = p.accent2, bold = true },
    MasonMuted = { fg = p.fg2 },
    MasonMutedBlock = { fg = p.fg2, bg = p.bg4 },
    MasonMutedBlockBold = { fg = p.fg2, bg = p.bg4, bold = true },
    MasonError = { fg = p.red },
    MasonWarning = { fg = p.yellow },
    MasonLink = { fg = p.blue, underline = true },

    -- mini.statusline
    MiniStatuslineModeNormal = { fg = p.bg3, bg = p.fg2, bold = true },
    MiniStatuslineModeInsert = { fg = p.bg3, bg = p.green, bold = true },
    MiniStatuslineModeVisual = { fg = p.bg3, bg = p.accent2, bold = true },
    MiniStatuslineModeReplace = { fg = p.bg3, bg = p.red, bold = true },
    MiniStatuslineModeCommand = { fg = p.bg3, bg = p.yellow, bold = true },
    MiniStatuslineModeOther = { fg = p.bg3, bg = p.blue, bold = true },
    MiniStatuslineDevinfo = { fg = p.fg1, bg = p.bg4 },
    MiniStatuslineFilename = { fg = p.fg1, bg = p.bg2 },
    MiniStatuslineFileinfo = { fg = p.fg1, bg = p.bg4 },
    MiniStatuslineInactive = { fg = p.fg3, bg = p.bg1 },

    -- mini.icons
    MiniIconsAzure = { fg = p.cyan },
    MiniIconsBlue = { fg = p.blue },
    MiniIconsCyan = { fg = p.cyan },
    MiniIconsGreen = { fg = p.green },
    MiniIconsGrey = { fg = p.fg2 },
    MiniIconsOrange = { fg = p.accent },
    MiniIconsPurple = { fg = p.purple },
    MiniIconsRed = { fg = p.red },
    MiniIconsWhite = { fg = p.fg0 },
    MiniIconsYellow = { fg = p.yellow },

    -- treesitter-context
    TreesitterContext = { bg = p.bg2 },
    TreesitterContextLineNumber = { fg = p.fg3, bg = p.bg2 },
    TreesitterContextBottom = { underline = true, sp = p.fg3 },
    TreesitterContextLineNumberBottom = { underline = true, sp = p.fg3 },
    TreesitterContextSeparator = { fg = p.fg3 },

    -- mini.clue
    MiniClueBorder = { fg = p.fg3, bg = p.bg0 },
    MiniClueDescGroup = { fg = p.blue },
    MiniClueDescSingle = { fg = p.fg0 },
    MiniClueNextKey = { fg = p.accent },
    MiniClueNextKeyWithPostkeys = { fg = p.accent, bold = true },
    MiniClueSeparator = { fg = p.fg3 },
    MiniClueTitle = { fg = p.accent, bg = p.bg0, bold = true },

    -- mini.surround
    MiniSurround = { fg = p.bg3, bg = p.accent },

    -- trouble.nvim
    TroubleNormal = { fg = p.fg0, bg = p.bg1 },
    TroubleNormalNC = { fg = p.fg0, bg = p.bg1 },
    TroubleCount = { fg = p.accent, bold = true },
    TroubleIconError = { fg = p.red },
    TroubleIconWarning = { fg = p.yellow },
    TroubleIconInformation = { fg = p.blue },
    TroubleIconHint = { fg = p.green },
    TroubleIconOther = { fg = p.fg2 },
    TroubleIconDirectory = { fg = p.blue },
    TroubleIconFile = { fg = p.fg0 },
    TroubleText = { fg = p.fg0 },
    TroubleTextError = { fg = p.red },
    TroubleTextWarning = { fg = p.yellow },
    TroubleTextInformation = { fg = p.blue },
    TroubleTextHint = { fg = p.green },
    TroubleCode = { fg = p.fg2 },
    TroubleSource = { fg = p.fg2 },
    TroublePos = { fg = p.fg3 },
    TroubleIndent = { fg = p.fg3 },
    TroubleIndentFoldOpen = { fg = p.accent },
    TroubleIndentFoldClosed = { fg = p.fg3 },
    TroubleIndentWs = { fg = p.fg3 },
    TroubleIndentTop = { fg = p.fg3 },
    TroubleIndentMiddle = { fg = p.fg3 },
    TroubleIndentLast = { fg = p.fg3 },
    TroubleAncestry = { fg = p.fg3 },
    TroubleBasename = { fg = p.fg0, bold = true },
    TroubleDirectory = { fg = p.blue },
    TroubleDirname = { fg = p.blue },
    TroubleFilename = { fg = p.fg0 },
    TroublePreview = { bg = p.bg4 },

    -- fzf-lua
    FzfLuaNormal = { fg = p.fg0, bg = p.bg1 },
    FzfLuaBorder = { fg = p.fg3, bg = p.bg1 },
    FzfLuaTitle = { fg = p.accent, bg = p.bg1, bold = true },
    FzfLuaPreviewNormal = { fg = p.fg0, bg = p.bg0 },
    FzfLuaPreviewBorder = { fg = p.fg3, bg = p.bg0 },
    FzfLuaPreviewTitle = { fg = p.accent2, bg = p.bg0, bold = true },
    FzfLuaCursor = { link = 'Cursor' },
    FzfLuaCursorLine = { link = 'CursorLine' },
    FzfLuaCursorLineNr = { link = 'CursorLineNr' },
    FzfLuaSearch = { link = 'Search' },
    FzfLuaScrollBorderEmpty = { fg = p.fg3, bg = p.bg1 },
    FzfLuaScrollBorderFull = { fg = p.accent, bg = p.bg1 },
    FzfLuaScrollFloatEmpty = { bg = p.bg2 },
    FzfLuaScrollFloatFull = { bg = p.accent },
    FzfLuaHelpNormal = { fg = p.fg0, bg = p.bg0 },
    FzfLuaHelpBorder = { fg = p.fg3, bg = p.bg0 },
    FzfLuaHeaderBind = { fg = p.accent2 },
    FzfLuaHeaderText = { fg = p.blue },
    FzfLuaPathColNr = { fg = p.fg3 },
    FzfLuaPathLineNr = { fg = p.fg3 },
    FzfLuaBufName = { fg = p.fg1 },
    FzfLuaBufNr = { fg = p.fg3 },
    FzfLuaBufFlagCur = { fg = p.accent },
    FzfLuaBufFlagAlt = { fg = p.accent2 },
    FzfLuaTabTitle = { fg = p.accent, bold = true },
    FzfLuaTabMarker = { fg = p.accent2 },
    FzfLuaDirIcon = { fg = p.blue },
    FzfLuaLiveSym = { fg = p.accent2 },
    FzfLuaLivePrompt = { fg = p.accent },
    FzfLuaFzfPrompt = { fg = p.accent },
    FzfLuaFzfQuery = { fg = p.fg0 },
    FzfLuaFzfMatch = { fg = p.accent, bold = true },
    FzfLuaFzfPointer = { fg = p.accent },
    FzfLuaFzfInfo = { fg = p.fg3 },

    -- claudecode.nvim
    ClaudeCodeDiffAdd = { bg = p.diff_add },
    ClaudeCodeDiffDelete = { bg = p.diff_del },
    ClaudeCodeDiffChange = { bg = p.diff_change },
    ClaudeCodeDiffText = { bg = p.diff_text },

    -- snacks.nvim (core window)
    SnacksNormal = { fg = p.fg0, bg = p.bg1 },
    SnacksNormalNC = { fg = p.fg0, bg = p.bg1 },
    SnacksBackdrop = { bg = p.bg0 },
    SnacksTitle = { fg = p.accent, bold = true },
    SnacksFooter = { link = 'FloatFooter' },
    SnacksFooterDesc = { fg = p.blue },
    SnacksFooterKey = { fg = p.accent2, bg = p.bg4 },
    SnacksWinBar = { fg = p.accent, bold = true },
    SnacksWinBarNC = { link = 'SnacksWinBar' },
    SnacksWinKey = { fg = p.accent },
    SnacksWinKeySep = { fg = p.fg3 },
    SnacksWinKeyDesc = { fg = p.fg0 },
    SnacksWinSeparator = { link = 'WinSeparator' },

    -- snacks.nvim (dashboard)
    SnacksDashboardNormal = { fg = p.fg0, bg = p.bg0 },
    SnacksDashboardDesc = { fg = p.fg1 },
    SnacksDashboardFile = { fg = p.accent },
    SnacksDashboardDir = { fg = p.fg3 },
    SnacksDashboardFooter = { fg = p.fg2, italic = true },
    SnacksDashboardHeader = { fg = p.accent, bold = true },
    SnacksDashboardIcon = { fg = p.blue },
    SnacksDashboardKey = { fg = p.accent2 },
    SnacksDashboardSpecial = { fg = p.accent },
    SnacksDashboardTitle = { fg = p.accent, bold = true },
    SnacksDashboardTerminal = { link = 'SnacksDashboardNormal' },

    -- snacks.nvim (notifier)
    SnacksNotifierHistory = { fg = p.fg0, bg = p.bg1 },
    SnacksNotifierHistoryTitle = { fg = p.accent, bold = true },
    SnacksNotifierHistoryDateTime = { fg = p.fg2 },
    SnacksNotifierMinimal = { link = 'NormalFloat' },
    SnacksNotifierIconTrace = { fg = p.fg3 },
    SnacksNotifierIconDebug = { fg = p.fg2 },
    SnacksNotifierIconInfo = { fg = p.blue },
    SnacksNotifierIconWarn = { fg = p.yellow },
    SnacksNotifierIconError = { fg = p.red },
    SnacksNotifierBorderTrace = { fg = p.fg3 },
    SnacksNotifierBorderDebug = { fg = p.fg2 },
    SnacksNotifierBorderInfo = { fg = p.blue },
    SnacksNotifierBorderWarn = { fg = p.yellow },
    SnacksNotifierBorderError = { fg = p.red },
    SnacksNotifierTitleTrace = { fg = p.fg3 },
    SnacksNotifierTitleDebug = { fg = p.fg2 },
    SnacksNotifierTitleInfo = { fg = p.blue },
    SnacksNotifierTitleWarn = { fg = p.yellow },
    SnacksNotifierTitleError = { fg = p.red },
    SnacksNotifierFooterTrace = { fg = p.fg3 },
    SnacksNotifierFooterDebug = { fg = p.fg2 },
    SnacksNotifierFooterInfo = { fg = p.blue },
    SnacksNotifierFooterWarn = { fg = p.yellow },
    SnacksNotifierFooterError = { fg = p.red },

    -- snacks.nvim (picker ui)
    SnacksPickerMatch = { fg = p.accent, bold = true },
    SnacksPickerSearch = { link = 'Search' },
    SnacksPickerPrompt = { fg = p.accent },
    SnacksPickerInputSearch = { fg = p.accent2 },
    SnacksPickerSpecial = { fg = p.accent },
    SnacksPickerLabel = { fg = p.accent },
    SnacksPickerToggle = { fg = p.blue, bg = p.bg4 },
    SnacksPickerSelected = { fg = p.accent, bold = true },
    SnacksPickerUnselected = { fg = p.fg3 },
    SnacksPickerSpinner = { fg = p.accent },
    SnacksPickerTotals = { fg = p.fg3 },
    SnacksPickerBold = { bold = true },
    SnacksPickerItalic = { italic = true },
    SnacksPickerDimmed = { fg = p.fg3 },
    SnacksPickerCode = { fg = p.green, bg = p.bg2 },
    SnacksPickerDelim = { fg = p.fg3 },
    SnacksPickerComment = { fg = p.fg2 },
    SnacksPickerDesc = { fg = p.fg2 },
    SnacksPickerIdx = { fg = p.accent2 },
    SnacksPickerRow = { fg = p.green },
    SnacksPickerCol = { fg = p.fg3 },
    SnacksPickerTree = { fg = p.fg3 },
    SnacksPickerTime = { fg = p.fg2 },
    SnacksPickerCmd = { fg = p.accent },
    SnacksPickerRule = { fg = p.fg3 },

    -- snacks.nvim (picker window)
    SnacksPickerList = { fg = p.fg0, bg = p.bg1 },
    SnacksPickerListCursorLine = { bg = p.bg4 },
    SnacksPickerInput = { fg = p.fg0, bg = p.bg1 },
    SnacksPickerBox = { link = 'SnacksNormal' },
    SnacksPickerPreview = { fg = p.fg0, bg = p.bg0 },
    SnacksPickerPreviewCursorLine = { bg = p.bg4 },
    SnacksPickerPickWin = { link = 'Search' },
    SnacksPickerPickWinCurrent = { link = 'CurSearch' },

    -- snacks.nvim (picker files)
    SnacksPickerFile = { fg = p.fg0 },
    SnacksPickerDir = { fg = p.fg3 },
    SnacksPickerDirectory = { fg = p.blue },
    SnacksPickerPathIgnored = { fg = p.fg3 },
    SnacksPickerPathHidden = { fg = p.fg3 },
    SnacksPickerLink = { fg = p.purple },
    SnacksPickerLinkBroken = { fg = p.red },

    -- snacks.nvim (picker git)
    SnacksPickerGitCommit = { fg = p.purple },
    SnacksPickerGitBreaking = { fg = p.red, bold = true },
    SnacksPickerGitDetached = { fg = p.yellow },
    SnacksPickerGitBranch = { fg = p.accent, bold = true },
    SnacksPickerGitBranchCurrent = { fg = p.green, bold = true },
    SnacksPickerGitDate = { fg = p.fg2 },
    SnacksPickerGitIssue = { fg = p.blue },
    SnacksPickerGitAuthor = { fg = p.fg1 },
    SnacksPickerGitType = { fg = p.accent, bold = true },
    SnacksPickerGitScope = { fg = p.fg1, italic = true },
    SnacksPickerGitMsg = { fg = p.fg1 },
    SnacksPickerGitStatus = { fg = p.accent },
    SnacksPickerGitStatusAdded = { fg = p.green },
    SnacksPickerGitStatusModified = { fg = p.yellow },
    SnacksPickerGitStatusDeleted = { fg = p.red },
    SnacksPickerGitStatusRenamed = { link = 'SnacksPickerGitStatus' },
    SnacksPickerGitStatusCopied = { link = 'SnacksPickerGitStatus' },
    SnacksPickerGitStatusUntracked = { fg = p.fg3 },
    SnacksPickerGitStatusIgnored = { fg = p.fg3 },
    SnacksPickerGitStatusUnmerged = { fg = p.red },
    SnacksPickerGitStatusStaged = { fg = p.green },

    -- snacks.nvim (picker misc)
    SnacksPickerRegister = { fg = p.accent2 },
    SnacksPickerBufNr = { fg = p.fg3 },
    SnacksPickerBufFlags = { fg = p.fg3 },
    SnacksPickerBufType = { fg = p.accent },
    SnacksPickerFileType = { fg = p.green },
    SnacksPickerDiagnosticCode = { fg = p.fg2 },
    SnacksPickerDiagnosticSource = { fg = p.fg2 },
    SnacksPickerUndoAdded = { fg = p.green },
    SnacksPickerUndoRemoved = { fg = p.red },
    SnacksPickerUndoCurrent = { fg = p.accent, bold = true },
    SnacksPickerUndoSaved = { fg = p.blue },
    SnacksPickerAuEvent = { fg = p.purple },
    SnacksPickerAuPattern = { fg = p.green },
    SnacksPickerAuGroup = { fg = p.blue },
    SnacksPickerKeymapMode = { fg = p.accent2 },
    SnacksPickerKeymapLhs = { fg = p.accent },
    SnacksPickerKeymapNowait = { fg = p.purple },
    SnacksPickerKeymapRhs = { fg = p.fg3 },
    SnacksPickerManPage = { fg = p.accent },
    SnacksPickerManSection = { fg = p.accent2 },
    SnacksPickerManDesc = { fg = p.fg1 },
    SnacksPickerLspDisabled = { fg = p.yellow },
    SnacksPickerLspEnabled = { fg = p.green },
    SnacksPickerLspAttached = { fg = p.yellow },
    SnacksPickerLspAttachedBuf = { fg = p.blue },
    SnacksPickerLspUnavailable = { fg = p.red },
    SnacksPickerNotificationMessage = { fg = p.fg0 },

    -- snacks.nvim (indent)
    SnacksIndent = { fg = p.indent },
    SnacksIndentBlank = { fg = p.indent },
    SnacksIndentScope = { fg = p.indent_active },
    SnacksIndentChunk = { fg = p.indent_active },

    -- snacks.nvim (input)
    SnacksInputNormal = { fg = p.fg0, bg = p.bg1 },
    SnacksInputIcon = { fg = p.accent },
    SnacksInputBorder = { fg = p.blue, bg = p.bg1 },
    SnacksInputTitle = { fg = p.blue, bold = true },
    SnacksInputPrompt = { link = 'SnacksInputTitle' },

    -- snacks.nvim (github)
    SnacksGhGreen = { fg = p.green },
    SnacksGhPurple = { fg = p.purple },
    SnacksGhGray = { fg = p.fg2 },
    SnacksGhRed = { fg = p.red },
    SnacksGhNumber = { fg = p.accent2 },
    SnacksGhBranch = { fg = p.accent },
    SnacksGhLabel = { fg = p.blue },
    SnacksGhDelim = { fg = p.fg3 },
    SnacksGhStat = { fg = p.fg2 },
    SnacksGhBotBadge = { fg = p.fg3 },
    SnacksGhScratchTitle = { fg = p.accent2 },
    SnacksGhScratchBorder = { fg = p.accent2 },

    -- snacks.nvim (dim, debug, scratch, statuscolumn, zen, image)
    SnacksDim = { fg = p.fg3 },
    SnacksDebugIndent = { fg = p.fg3 },
    SnacksDebugPrint = { fg = p.fg3 },
    SnacksScratchTitle = { link = 'FloatTitle' },
    SnacksStatusColumnMark = { fg = p.accent },
    SnacksZenIcon = { fg = p.yellow },
    SnacksImageSpinner = { fg = p.accent },
    SnacksImageLoading = { fg = p.fg3 },
    SnacksImageAnchor = { fg = p.accent },

    -- NvimTree
    NvimTreeNormal = { fg = p.fg0, bg = p.bg1 },
    NvimTreeNormalNC = { fg = p.fg0, bg = p.bg1 },
    NvimTreeWinSeparator = { fg = p.bg4, bg = p.bg1 },
    NvimTreeEndOfBuffer = { fg = p.bg1 },
    NvimTreeCursorLine = { bg = p.bg4 },
    NvimTreeRootFolder = { fg = p.accent, bold = true },
    NvimTreeFolderName = { fg = p.blue },
    NvimTreeFolderIcon = { fg = p.blue },
    NvimTreeOpenedFolderName = { fg = p.blue, bold = true },
    NvimTreeEmptyFolderName = { fg = p.fg3 },
    NvimTreeSymlinkFolderName = { fg = p.purple },
    NvimTreeFileName = { fg = p.fg0 },
    NvimTreeOpenedFile = { fg = p.fg0, bold = true },
    NvimTreeModifiedFile = { fg = p.yellow },
    NvimTreeSpecialFile = { fg = p.accent2 },
    NvimTreeSymlink = { fg = p.purple },
    NvimTreeIndentMarker = { fg = p.fg3 },
    NvimTreeImageFile = { fg = p.purple },
    NvimTreeGitDirty = { fg = p.yellow },
    NvimTreeGitStaged = { fg = p.green },
    NvimTreeGitMerge = { fg = p.accent },
    NvimTreeGitRenamed = { fg = p.purple },
    NvimTreeGitNew = { fg = p.green },
    NvimTreeGitDeleted = { fg = p.red },
    NvimTreeGitIgnored = { fg = p.fg3 },
    NvimTreeDiagnosticErrorIcon = { fg = p.red },
    NvimTreeDiagnosticWarnIcon = { fg = p.yellow },
    NvimTreeDiagnosticInfoIcon = { fg = p.blue },
    NvimTreeDiagnosticHintIcon = { fg = p.green },
  }
end

return plugins
